### ISSUE TITLE
unrecognized arguments: --numRayMarchSamples 8 --numRayMarchSamples 8

### ISSUE THREAD

**Issue by chensjtu** [thomasneff/AdaNeRF#2]
I encountered this issue when using train.py fine_training, this opt is not an option.

**Comment by chensjtu** [comment]
maybe this one should be specified in fine_training.ini?

**Comment by thomasneff** [comment]
Hi, sorry for that, our README had a typo in there with `numRaymarchSamples` (it was specified as `numRayMarchSamples` where it should have been `numRaymarchSamples` as defined in the config files).

Should be fixed in the README now, thanks for letting us know!
