### ISSUE TITLE
Generate more images!

### ISSUE THREAD

**Issue by chensjtu** [thomasneff/AdaNeRF#3]
Thanks for your wonderful work! Since the scene in DONeRF dataset is pretty large, I wonder if you can share the generation code of the DONeRF dataset so that I can apply adanerf for more positions.

**Comment by thomasneff** [comment]
Hey there! I just added two python files (`blender_export_per_scene_stub.py` and `blender_export.py`) with a short explanation in the README that can be used with Blender to generate additional data. These should hopefully be easy enough to set up.

**Comment by chensjtu** [comment]
I'm not familiar with Blender, so I wonder "the RENDER_IMG_NAME variable needs to be set to the compositor node that exports the depth image in Blender." means. In fact, I connect view layer to Render Layers, but the depth is nothing. 
<img width="436" alt="image" src="https://user-images.githubusercontent.com/38242929/186117073-1c376604-6fd9-4059-9715-ae5a458ca498.png">
